/* ============================================
   SHIMMERS BAKERY — Product Data
   ============================================ */

const SHOP_INFO = {
  name: "Shimmers",
  tagline: "Where Every Bite Sparkles ✨",
  address: "42, Rose Garden Lane, Near City Centre Mall, Blossom Nagar, Jaipur — 302017",
  phone: "+91 98765 43210",
  email: "hello@shimmersbakery.in",
  hours: "9:00 AM — 9:00 PM (Mon–Sun)",
  instagram: "@shimmersbakery",
};

const DISCOUNT_CODES = {
  SHIMMER10: { percent: 10, label: "10% Off ✨" },
  SWEETDEAL: { percent: 15, label: "15% Off 🍰" },
  SPARKLE20: { percent: 20, label: "20% Off 🎉" },
};

const CUSTOMIZATION_OPTIONS = {
  weights: [
    { label: "0.5 kg", value: 0.5, priceMultiplier: 0.6 },
    { label: "1 kg", value: 1, priceMultiplier: 1 },
    { label: "1.5 kg", value: 1.5, priceMultiplier: 1.4 },
    { label: "2 kg", value: 2, priceMultiplier: 1.8 },
    { label: "3 kg", value: 3, priceMultiplier: 2.6 },
  ],
  baseFlavors: [
    "Vanilla Sponge", "Chocolate Sponge", "Red Velvet", "Butterscotch",
    "Pineapple", "Strawberry", "Coffee", "Marble"
  ],
  toppingFlavors: [
    "Buttercream", "Whipped Cream", "Chocolate Ganache", "Cream Cheese",
    "Fondant", "Fresh Fruit", "Caramel Drizzle", "Strawberry Glaze"
  ],
  addOns: [
    { name: "Sprinkles", price: 50, emoji: "🌈" },
    { name: "Chocolate Chips", price: 80, emoji: "🍫" },
    { name: "Chopped Nuts", price: 100, emoji: "🥜" },
    { name: "Fresh Fruit Topping", price: 150, emoji: "🍓" },
    { name: "Edible Glitter", price: 120, emoji: "✨" },
    { name: "Fondant Decorations", price: 200, emoji: "🎀" },
    { name: "Cake Topper", price: 180, emoji: "🎂" },
    { name: "Extra Layer", price: 250, emoji: "📚" },
    { name: "Photo Print (Edible)", price: 300, emoji: "📸" },
    { name: "Candles Set", price: 60, emoji: "🕯️" },
  ],
  tiers: [
    { label: "Single Tier", value: 1, priceExtra: 0 },
    { label: "Two Tier", value: 2, priceExtra: 500 },
    { label: "Three Tier", value: 3, priceExtra: 1200 },
  ],
};

const CATEGORIES = [
  {
    id: "cakes",
    name: "Cakes",
    emoji: "🎂",
    color: "var(--pink-300)",
    bgGradient: "linear-gradient(135deg, #ffd6e7 0%, #ffadd2 100%)",
    description: "Freshly baked cakes made with love & finest ingredients",
    sticker: "🍰",
  },
  {
    id: "cookies",
    name: "Cookies",
    emoji: "🍪",
    color: "var(--yellow-400)",
    bgGradient: "linear-gradient(135deg, #fef9c3 0%, #fde68a 100%)",
    description: "Crunchy, crumbly cookies in unique Indian flavours",
    sticker: "✨",
  },
  {
    id: "snacks",
    name: "Snacks",
    emoji: "🥐",
    color: "var(--beige-400)",
    bgGradient: "linear-gradient(135deg, #fdf6e3 0%, #f5e6c8 100%)",
    description: "Savory and crispy baked snacks for tea time",
    sticker: "☕",
  },
  {
    id: "desserts",
    name: "Desserts",
    emoji: "🍮",
    color: "var(--green-400)",
    bgGradient: "linear-gradient(135deg, #d1fae5 0%, #a7f3d0 100%)",
    description: "Indulgent desserts that melt in your mouth",
    sticker: "🌿",
  },
  {
    id: "pastries",
    name: "Pastries",
    emoji: "🥮",
    color: "var(--blue-300)",
    bgGradient: "linear-gradient(135deg, #bae6fd 0%, #7dd3fc 100%)",
    description: "Flaky, buttery pastries baked to golden perfection",
    sticker: "🧈",
  },
  {
    id: "beverages",
    name: "Beverages",
    emoji: "🧃",
    color: "var(--yellow-300)",
    bgGradient: "linear-gradient(135deg, #fde68a 0%, #fbbf24 100%)",
    description: "Cool refreshments to pair with your treats",
    sticker: "🍹",
  },
  {
    id: "specials",
    name: "Specials",
    emoji: "⭐",
    color: "var(--pink-400)",
    bgGradient: "linear-gradient(135deg, #ffadd2 0%, #ff85b3 100%)",
    description: "Our chef's special creations — limited & exclusive!",
    sticker: "💫",
  },
];

const PRODUCTS = {
  cakes: [
    {
      id: "old-school-chocolate",
      name: "Old School Chocolate Cake",
      price: 650,
      description: "A timeless classic — rich, moist chocolate sponge layered with velvety chocolate buttercream. Just like grandma used to make!",
      ingredients: ["Flour", "Cocoa Powder", "Sugar", "Eggs", "Butter", "Milk", "Vanilla Extract", "Baking Powder"],
      allergens: ["Gluten", "Dairy", "Eggs"],
      weight: "1 kg",
      sticker: "🍫",
      stickerLabel: "Choco Drizzle",
      bgColor: "#4a2c2a",
      cardGradient: "linear-gradient(135deg, #6b3a2a 0%, #4a2020 100%)",
      textLight: true,
      customizable: true,
    },
    {
      id: "cookie-and-cream",
      name: "Cookie & Cream Cake",
      price: 750,
      description: "Crushed Oreo cookies folded into fluffy vanilla cream, layered between soft chocolate sponge. Cookies & cream heaven!",
      ingredients: ["Flour", "Sugar", "Eggs", "Butter", "Cream", "Oreo Cookies", "Vanilla", "Milk"],
      allergens: ["Gluten", "Dairy", "Eggs", "Soy"],
      weight: "1 kg",
      sticker: "🍪",
      stickerLabel: "Cookie Crumble",
      bgColor: "#2d2d2d",
      cardGradient: "linear-gradient(135deg, #f5f0eb 0%, #d4ccc4 100%)",
      textLight: false,
      customizable: true,
    },
    {
      id: "chocolate-crunch",
      name: "Chocolate Crunch Cake",
      price: 800,
      description: "Loaded with crispy wafer crunch and chocolate shards on a deep chocolate base. Every bite is an adventure in texture!",
      ingredients: ["Flour", "Cocoa", "Sugar", "Eggs", "Butter", "Wafer Crunch", "Dark Chocolate", "Cream"],
      allergens: ["Gluten", "Dairy", "Eggs", "Nuts"],
      weight: "1 kg",
      sticker: "💥",
      stickerLabel: "Crunchy Bits",
      bgColor: "#3d1f0a",
      cardGradient: "linear-gradient(135deg, #8B4513 0%, #5c2d0e 100%)",
      textLight: true,
      customizable: true,
    },
    {
      id: "buttery-caramel",
      name: "Buttery Caramel Cake",
      price: 850,
      description: "Golden caramel swirled through buttery vanilla layers, topped with salted caramel drizzle and toffee bits. Pure indulgence!",
      ingredients: ["Flour", "Sugar", "Butter", "Eggs", "Caramel", "Salt", "Cream", "Vanilla", "Toffee"],
      allergens: ["Gluten", "Dairy", "Eggs"],
      weight: "1 kg",
      sticker: "🍯",
      stickerLabel: "Caramel Swirl",
      bgColor: "#b8860b",
      cardGradient: "linear-gradient(135deg, #fde68a 0%, #d4a017 100%)",
      textLight: false,
      customizable: true,
    },
    {
      id: "kitkat",
      name: "KitKat Cake",
      price: 900,
      description: "Chocolate sponge surrounded by KitKat fingers, topped with M&Ms and chocolate ganache. A candy lover's dream cake!",
      ingredients: ["Flour", "Cocoa", "Sugar", "Eggs", "Butter", "KitKat", "M&Ms", "Chocolate", "Cream"],
      allergens: ["Gluten", "Dairy", "Eggs", "Nuts", "Soy"],
      weight: "1 kg",
      sticker: "🟫",
      stickerLabel: "KitKat Bar",
      bgColor: "#8B0000",
      cardGradient: "linear-gradient(135deg, #cc2936 0%, #8B0000 100%)",
      textLight: true,
      customizable: true,
    },
    {
      id: "chocolate-almond",
      name: "Chocolate Almond Cake",
      price: 850,
      description: "Rich Belgian chocolate cake studded with roasted almonds and finished with almond praline. Nutty, chocolatey perfection!",
      ingredients: ["Flour", "Cocoa", "Sugar", "Eggs", "Butter", "Almonds", "Dark Chocolate", "Cream", "Almond Extract"],
      allergens: ["Gluten", "Dairy", "Eggs", "Tree Nuts"],
      weight: "1 kg",
      sticker: "🌰",
      stickerLabel: "Almond Crunch",
      bgColor: "#5c3317",
      cardGradient: "linear-gradient(135deg, #8B6914 0%, #5c3317 100%)",
      textLight: true,
      customizable: true,
    },
    {
      id: "strawberries",
      name: "Strawberries Cake",
      price: 800,
      description: "Light vanilla sponge layered with fresh strawberry compote and whipped cream, crowned with glazed strawberries. Berry delicious!",
      ingredients: ["Flour", "Sugar", "Eggs", "Butter", "Strawberries", "Cream", "Vanilla", "Gelatin"],
      allergens: ["Gluten", "Dairy", "Eggs"],
      weight: "1 kg",
      sticker: "🍓",
      stickerLabel: "Fresh Strawberry",
      bgColor: "#c41e3a",
      cardGradient: "linear-gradient(135deg, #ffc0cb 0%, #ff69b4 100%)",
      textLight: false,
      customizable: true,
    },
  ],

  cookies: [
    {
      id: "jeera",
      name: "Jeera Cookies",
      price: 180,
      description: "Aromatic cumin-spiced butter cookies with a subtle crunch. A uniquely Indian twist on the classic biscuit — perfect with chai!",
      ingredients: ["Flour", "Butter", "Sugar", "Cumin Seeds (Jeera)", "Salt", "Baking Powder"],
      allergens: ["Gluten", "Dairy"],
      weight: "250g pack",
      sticker: "🫘",
      stickerLabel: "Jeera Seeds",
      bgColor: "#d4a574",
      cardGradient: "linear-gradient(135deg, #f5e6c8 0%, #d4a574 100%)",
      textLight: false,
      customizable: false,
    },
    {
      id: "coconut",
      name: "Coconut Cookies",
      price: 180,
      description: "Crispy cookies loaded with desiccated coconut and a hint of cardamom. Tropical vibes in every bite!",
      ingredients: ["Flour", "Butter", "Sugar", "Desiccated Coconut", "Cardamom", "Baking Powder"],
      allergens: ["Gluten", "Dairy", "Coconut"],
      weight: "250g pack",
      sticker: "🥥",
      stickerLabel: "Coconut Flakes",
      bgColor: "#f5f0eb",
      cardGradient: "linear-gradient(135deg, #fefcf3 0%, #e8d5a3 100%)",
      textLight: false,
      customizable: false,
    },
    {
      id: "tutti-frutti",
      name: "Tutti Frutti Cookies",
      price: 200,
      description: "Cheerful, colourful cookies dotted with tutti frutti bits. Fun, fruity, and an absolute kids' favourite!",
      ingredients: ["Flour", "Butter", "Sugar", "Tutti Frutti", "Vanilla", "Baking Powder", "Milk"],
      allergens: ["Gluten", "Dairy"],
      weight: "250g pack",
      sticker: "🌈",
      stickerLabel: "Rainbow Bits",
      bgColor: "#ff85b3",
      cardGradient: "linear-gradient(135deg, #ffd6e7 0%, #bae6fd 100%)",
      textLight: false,
      customizable: false,
    },
    {
      id: "oats",
      name: "Oats Cookies",
      price: 200,
      description: "Wholesome oat cookies with honey and a touch of cinnamon. Guilt-free snacking that actually tastes amazing!",
      ingredients: ["Rolled Oats", "Flour", "Honey", "Butter", "Brown Sugar", "Cinnamon", "Baking Soda"],
      allergens: ["Gluten", "Dairy"],
      weight: "250g pack",
      sticker: "🌾",
      stickerLabel: "Oat Flakes",
      bgColor: "#c9b896",
      cardGradient: "linear-gradient(135deg, #fdf6e3 0%, #c9b896 100%)",
      textLight: false,
      customizable: false,
    },
  ],

  snacks: [
    {
      id: "rusks",
      name: "Rusks",
      price: 150,
      description: "Double-baked, golden-brown rusks — perfectly crispy and lightly sweet. The ultimate chai-dunking companion!",
      ingredients: ["Flour", "Sugar", "Butter", "Eggs", "Yeast", "Cardamom", "Milk"],
      allergens: ["Gluten", "Dairy", "Eggs"],
      weight: "300g pack",
      sticker: "☕",
      stickerLabel: "Chai Time",
      bgColor: "#d4a574",
      cardGradient: "linear-gradient(135deg, #f5e6c8 0%, #d4a574 100%)",
      textLight: false,
      customizable: false,
    },
    {
      id: "rolls",
      name: "Rolls",
      price: 120,
      description: "Soft, fluffy bread rolls with a golden crust. Fresh from the oven — perfect for sandwiches or as a snack on their own!",
      ingredients: ["Flour", "Yeast", "Butter", "Sugar", "Salt", "Milk", "Eggs"],
      allergens: ["Gluten", "Dairy", "Eggs"],
      weight: "Pack of 6",
      sticker: "🍞",
      stickerLabel: "Fresh Baked",
      bgColor: "#c49a6c",
      cardGradient: "linear-gradient(135deg, #fdf6e3 0%, #c49a6c 100%)",
      textLight: false,
      customizable: false,
    },
    {
      id: "kharis",
      name: "Kharis",
      price: 160,
      description: "Flaky, puffed khari biscuits with layers of buttery goodness. Salty, crispy, and absolutely addictive with a cup of tea!",
      ingredients: ["Flour", "Butter", "Salt", "Cumin", "Ajwain"],
      allergens: ["Gluten", "Dairy"],
      weight: "250g pack",
      sticker: "🧈",
      stickerLabel: "Buttery Layers",
      bgColor: "#e8d5a3",
      cardGradient: "linear-gradient(135deg, #fefcf3 0%, #e8d5a3 100%)",
      textLight: false,
      customizable: false,
    },
  ],

  desserts: [
    {
      id: "orange-french-cream",
      name: "Orange French Cream",
      price: 350,
      description: "Silky French cream infused with fresh orange zest, served in a delicate glass. Light, citrusy, and utterly elegant!",
      ingredients: ["Cream", "Sugar", "Orange Zest", "Orange Juice", "Gelatin", "Vanilla"],
      allergens: ["Dairy"],
      weight: "Serves 1",
      sticker: "🍊",
      stickerLabel: "Orange Zest",
      bgColor: "#ff8c00",
      cardGradient: "linear-gradient(135deg, #fde68a 0%, #ff8c00 100%)",
      textLight: false,
      customizable: false,
    },
    {
      id: "brownie",
      name: "Brownie",
      price: 180,
      description: "Fudgy, gooey chocolate brownies with a crackly top and molten centre. Chocolate therapy in every square!",
      ingredients: ["Dark Chocolate", "Butter", "Sugar", "Eggs", "Flour", "Cocoa Powder", "Vanilla"],
      allergens: ["Gluten", "Dairy", "Eggs"],
      weight: "1 piece (~100g)",
      sticker: "🍫",
      stickerLabel: "Choco Fudge",
      bgColor: "#3d1f0a",
      cardGradient: "linear-gradient(135deg, #6b3a2a 0%, #3d1f0a 100%)",
      textLight: true,
      customizable: false,
    },
  ],

  pastries: [
    {
      id: "croissant",
      name: "Croissant",
      price: 120,
      description: "Golden, buttery croissant with perfectly flaky layers. Baked fresh every morning — Paris in Jaipur!",
      ingredients: ["Flour", "Butter", "Sugar", "Yeast", "Salt", "Milk", "Eggs"],
      allergens: ["Gluten", "Dairy", "Eggs"],
      weight: "1 piece",
      sticker: "🥐",
      stickerLabel: "Flaky Layers",
      bgColor: "#d4a574",
      cardGradient: "linear-gradient(135deg, #fdf6e3 0%, #d4a574 100%)",
      textLight: false,
      customizable: false,
    },
    {
      id: "danish-pastry",
      name: "Danish Pastry",
      price: 150,
      description: "Flaky Danish pastry swirled with custard cream and topped with icing glaze. Light, sweet, and absolutely dreamy!",
      ingredients: ["Flour", "Butter", "Sugar", "Eggs", "Custard Cream", "Icing Sugar", "Yeast"],
      allergens: ["Gluten", "Dairy", "Eggs"],
      weight: "1 piece",
      sticker: "🌀",
      stickerLabel: "Cream Swirl",
      bgColor: "#e8b960",
      cardGradient: "linear-gradient(135deg, #fef9c3 0%, #e8b960 100%)",
      textLight: false,
      customizable: false,
    },
    {
      id: "puff-pastry",
      name: "Puff Pastry",
      price: 100,
      description: "Classic puff pastry — light as air with hundreds of golden, crispy layers. Filled with spiced potato or paneer!",
      ingredients: ["Flour", "Butter", "Salt", "Water", "Potato/Paneer Filling", "Spices"],
      allergens: ["Gluten", "Dairy"],
      weight: "1 piece",
      sticker: "💨",
      stickerLabel: "Light & Puffy",
      bgColor: "#c49a6c",
      cardGradient: "linear-gradient(135deg, #f5e6c8 0%, #c49a6c 100%)",
      textLight: false,
      customizable: false,
    },
    {
      id: "eclair",
      name: "Éclair",
      price: 160,
      description: "Choux pastry filled with silky vanilla cream and glazed with rich chocolate. French elegance in every bite!",
      ingredients: ["Flour", "Butter", "Eggs", "Cream", "Sugar", "Dark Chocolate", "Vanilla"],
      allergens: ["Gluten", "Dairy", "Eggs"],
      weight: "1 piece",
      sticker: "🍫",
      stickerLabel: "Choco Glaze",
      bgColor: "#4a2c2a",
      cardGradient: "linear-gradient(135deg, #d4a574 0%, #4a2c2a 100%)",
      textLight: true,
      customizable: false,
    },
  ],

  beverages: [
    {
      id: "frooti",
      name: "Frooti",
      price: 30,
      description: "India's favourite mango drink! Chilled, sweet, and refreshing — the perfect companion to your bakery treats.",
      ingredients: ["Mango Pulp", "Sugar", "Water", "Citric Acid"],
      allergens: [],
      weight: "200ml",
      sticker: "🥭",
      stickerLabel: "Mango Fresh",
      bgColor: "#fbbf24",
      cardGradient: "linear-gradient(135deg, #fef9c3 0%, #fbbf24 100%)",
      textLight: false,
      customizable: false,
    },
    {
      id: "chips",
      name: "Chips",
      price: 40,
      description: "Crispy, salted potato chips — the classic crunchy companion. Grab a pack to go with your sweet treats!",
      ingredients: ["Potato", "Vegetable Oil", "Salt"],
      allergens: [],
      weight: "50g pack",
      sticker: "🥔",
      stickerLabel: "Crunchy Bites",
      bgColor: "#f59e0b",
      cardGradient: "linear-gradient(135deg, #fde68a 0%, #f59e0b 100%)",
      textLight: false,
      customizable: false,
    },
  ],

  specials: [
    {
      id: "cream-rolls",
      name: "Cream Rolls",
      price: 80,
      description: "Flaky pastry tubes filled with luscious vanilla whipped cream. A beloved Indian bakery classic — our bestseller!",
      ingredients: ["Flour", "Butter", "Sugar", "Cream", "Vanilla", "Salt"],
      allergens: ["Gluten", "Dairy"],
      weight: "1 piece",
      sticker: "🌟",
      stickerLabel: "Bestseller",
      bgColor: "#fffdf7",
      cardGradient: "linear-gradient(135deg, #fff0f5 0%, #ffd6e7 100%)",
      textLight: false,
      customizable: false,
    },
    {
      id: "glass-cake",
      name: "Glass Cake",
      price: 250,
      description: "Stunning layered dessert served in a glass — alternating cake, cream, fruit, and jelly. Almost too pretty to eat!",
      ingredients: ["Sponge Cake", "Cream", "Fruit", "Jelly", "Sugar", "Gelatin"],
      allergens: ["Gluten", "Dairy", "Eggs"],
      weight: "Serves 1",
      sticker: "🔮",
      stickerLabel: "Crystal Clear",
      bgColor: "#e0f2fe",
      cardGradient: "linear-gradient(135deg, #bae6fd 0%, #7dd3fc 100%)",
      textLight: false,
      customizable: false,
    },
    {
      id: "cake-pops",
      name: "Cake Pops",
      price: 120,
      description: "Adorable cake balls on sticks, dipped in colourful chocolate coatings and decorated with sprinkles. Party on a stick!",
      ingredients: ["Cake Crumbs", "Cream Cheese", "Chocolate Coating", "Sprinkles", "Sugar"],
      allergens: ["Gluten", "Dairy", "Eggs", "Soy"],
      weight: "Pack of 3",
      sticker: "🍭",
      stickerLabel: "Party Pop",
      bgColor: "#ff85b3",
      cardGradient: "linear-gradient(135deg, #ffadd2 0%, #ff85b3 100%)",
      textLight: false,
      customizable: false,
    },
  ],
};
